// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProyectoV2.Models;

namespace ProyectoV2.Migrations
{
    [DbContext(typeof(SoftwareContext))]
    [Migration("20191218013218_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ProyectoV2.Models.Administrador", b =>
                {
                    b.Property<string>("Usuario")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rol")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Usuario");

                    b.ToTable("Administradores");
                });

            modelBuilder.Entity("ProyectoV2.Models.Asignatura", b =>
                {
                    b.Property<string>("AsignaturaId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CoRequisitos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NatAsignatura1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NatAsignatura2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ncreditos")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PreRequisitos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("programaId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("AsignaturaId");

                    b.HasIndex("programaId");

                    b.ToTable("Asignaturas");
                });

            modelBuilder.Entity("ProyectoV2.Models.CargaAcademica", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("id");

                    b.ToTable("CargaAcademicas");
                });

            modelBuilder.Entity("ProyectoV2.Models.Docente", b =>
                {
                    b.Property<string>("Identificacion")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrimerApellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrimerNombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rol")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SegundoApellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SegundoNombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("programaId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Identificacion");

                    b.HasIndex("programaId");

                    b.ToTable("Docentes");
                });

            modelBuilder.Entity("ProyectoV2.Models.EjeTematico", b =>
                {
                    b.Property<int>("EjeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AsignaturaId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EjeId");

                    b.HasIndex("AsignaturaId");

                    b.ToTable("EjeTematicos");
                });

            modelBuilder.Entity("ProyectoV2.Models.Estudiante", b =>
                {
                    b.Property<int>("EstudianteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Correo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GrupoId")
                        .HasColumnType("int");

                    b.Property<string>("Identificacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrimerApellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrimerNombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SegundoApellido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SegundoNombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EstudianteId");

                    b.HasIndex("GrupoId");

                    b.ToTable("Estudiantes");
                });

            modelBuilder.Entity("ProyectoV2.Models.Facultad", b =>
                {
                    b.Property<int>("facultadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("facultadId");

                    b.ToTable("Facultades");
                });

            modelBuilder.Entity("ProyectoV2.Models.Grupo", b =>
                {
                    b.Property<int>("GrupoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AsignaturaId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DocenteId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("numero")
                        .HasColumnType("int");

                    b.HasKey("GrupoId");

                    b.HasIndex("AsignaturaId");

                    b.HasIndex("DocenteId");

                    b.ToTable("Grupos");
                });

            modelBuilder.Entity("ProyectoV2.Models.ItemPlanDesarrollo", b =>
                {
                    b.Property<int>("IdPlan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Ano")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Competencias")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EjeTematicoId")
                        .HasColumnType("int");

                    b.Property<string>("Estrategias")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FechaFin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FechaInicio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GrupoId")
                        .HasColumnType("int");

                    b.Property<string>("Periodo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Referencias")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrabajoIndependiente")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdPlan");

                    b.HasIndex("EjeTematicoId");

                    b.HasIndex("GrupoId");

                    b.ToTable("ItemPlanesDesarrollo");
                });

            modelBuilder.Entity("ProyectoV2.Models.Programa", b =>
                {
                    b.Property<string>("programaId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("FacultadId")
                        .HasColumnType("int");

                    b.Property<int>("duracionSementral")
                        .HasColumnType("int");

                    b.Property<string>("horario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("metodologia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nombrePro")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("programaId");

                    b.HasIndex("FacultadId");

                    b.ToTable("Programas");
                });

            modelBuilder.Entity("ProyectoV2.Models.Tema", b =>
                {
                    b.Property<int>("TemaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("EjeTematicoId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TemaId");

                    b.HasIndex("EjeTematicoId");

                    b.ToTable("Temas");
                });

            modelBuilder.Entity("ProyectoV2.Models.TemaIP", b =>
                {
                    b.Property<int>("TemaIPId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ItemPlanDesarrolloIdPlan")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TemaIPId");

                    b.HasIndex("ItemPlanDesarrolloIdPlan");

                    b.ToTable("TemasIP");
                });

            modelBuilder.Entity("ProyectoV2.Models.Asignatura", b =>
                {
                    b.HasOne("ProyectoV2.Models.Programa", "Programa")
                        .WithMany()
                        .HasForeignKey("programaId");
                });

            modelBuilder.Entity("ProyectoV2.Models.Docente", b =>
                {
                    b.HasOne("ProyectoV2.Models.Programa", "Programa")
                        .WithMany()
                        .HasForeignKey("programaId");
                });

            modelBuilder.Entity("ProyectoV2.Models.EjeTematico", b =>
                {
                    b.HasOne("ProyectoV2.Models.Asignatura", "Asignatura")
                        .WithMany()
                        .HasForeignKey("AsignaturaId");
                });

            modelBuilder.Entity("ProyectoV2.Models.Estudiante", b =>
                {
                    b.HasOne("ProyectoV2.Models.Grupo", "Grupo")
                        .WithMany()
                        .HasForeignKey("GrupoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProyectoV2.Models.Grupo", b =>
                {
                    b.HasOne("ProyectoV2.Models.Asignatura", "Asignatura")
                        .WithMany()
                        .HasForeignKey("AsignaturaId");

                    b.HasOne("ProyectoV2.Models.Docente", "Docente")
                        .WithMany()
                        .HasForeignKey("DocenteId");
                });

            modelBuilder.Entity("ProyectoV2.Models.ItemPlanDesarrollo", b =>
                {
                    b.HasOne("ProyectoV2.Models.EjeTematico", "EjeTematico")
                        .WithMany()
                        .HasForeignKey("EjeTematicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProyectoV2.Models.Grupo", "grupo")
                        .WithMany()
                        .HasForeignKey("GrupoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProyectoV2.Models.Programa", b =>
                {
                    b.HasOne("ProyectoV2.Models.Facultad", "Facultad")
                        .WithMany()
                        .HasForeignKey("FacultadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProyectoV2.Models.Tema", b =>
                {
                    b.HasOne("ProyectoV2.Models.EjeTematico", null)
                        .WithMany("Temas")
                        .HasForeignKey("EjeTematicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProyectoV2.Models.TemaIP", b =>
                {
                    b.HasOne("ProyectoV2.Models.ItemPlanDesarrollo", null)
                        .WithMany("TemasIP")
                        .HasForeignKey("ItemPlanDesarrolloIdPlan");
                });
#pragma warning restore 612, 618
        }
    }
}
