// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProyectoV2.Models;

namespace ProyectoV2.Migrations
{
    [DbContext(typeof(SoftwareContext))]
    partial class SoftwareContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ProyectoV2.Models.Asignatura", b =>
                {
                    b.Property<string>("AsignaturaId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CoRequisitos")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NatAsignatura1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NatAsignatura2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ncreditos")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PreRequisitos")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("programaId")
                        .HasColumnType("int");

                    b.HasKey("AsignaturaId");

                    b.HasIndex("programaId");

                    b.ToTable("Asignaturas");
                });

            modelBuilder.Entity("ProyectoV2.Models.CargaAcademica", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("id");

                    b.ToTable("CargaAcademicas");
                });

            modelBuilder.Entity("ProyectoV2.Models.Docente", b =>
                {
                    b.Property<string>("Identificacion")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrimerApellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrimerNombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SegundoApellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SegundoNombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("programaId")
                        .HasColumnType("int");

                    b.HasKey("Identificacion");

                    b.HasIndex("programaId");

                    b.ToTable("Docentes");
                });

            modelBuilder.Entity("ProyectoV2.Models.EjeTematico", b =>
                {
                    b.Property<int>("EjeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AsignaturaId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EjeId");

                    b.HasIndex("AsignaturaId");

                    b.ToTable("EjeTematicos");
                });

            modelBuilder.Entity("ProyectoV2.Models.Estudiante", b =>
                {
                    b.Property<int>("IdEstudiante")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CargaAcademicaid")
                        .HasColumnType("int");

                    b.Property<int>("CargaId")
                        .HasColumnType("int");

                    b.Property<string>("Correo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Identificacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrimerApellido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrimerNombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SegundoApellido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SegundoNombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdEstudiante");

                    b.HasIndex("CargaAcademicaid");

                    b.ToTable("Estudiantes");
                });

            modelBuilder.Entity("ProyectoV2.Models.Facultad", b =>
                {
                    b.Property<int>("facultadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("facultadId");

                    b.ToTable("Facultades");
                });

            modelBuilder.Entity("ProyectoV2.Models.Grupo", b =>
                {
                    b.Property<int>("GrupoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AsignaturaId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DocenteId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("numero")
                        .HasColumnType("int");

                    b.HasKey("GrupoId");

                    b.HasIndex("AsignaturaId");

                    b.HasIndex("DocenteId");

                    b.ToTable("Grupos");
                });

            modelBuilder.Entity("ProyectoV2.Models.Programa", b =>
                {
                    b.Property<int>("programaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("FacultadId")
                        .HasColumnType("int");

                    b.Property<int>("duracionSementral")
                        .HasColumnType("int");

                    b.Property<string>("horario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("metodologia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nombrePro")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("programaId");

                    b.HasIndex("FacultadId");

                    b.ToTable("Programas");
                });

            modelBuilder.Entity("ProyectoV2.Models.Tema", b =>
                {
                    b.Property<int>("TemaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("EjeTematicoId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TemaId");

                    b.HasIndex("EjeTematicoId");

                    b.ToTable("Temas");
                });

            modelBuilder.Entity("ProyectoV2.Models.Asignatura", b =>
                {
                    b.HasOne("ProyectoV2.Models.Programa", "Programa")
                        .WithMany()
                        .HasForeignKey("programaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProyectoV2.Models.Docente", b =>
                {
                    b.HasOne("ProyectoV2.Models.Programa", "Programa")
                        .WithMany()
                        .HasForeignKey("programaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProyectoV2.Models.EjeTematico", b =>
                {
                    b.HasOne("ProyectoV2.Models.Asignatura", "Asignatura")
                        .WithMany()
                        .HasForeignKey("AsignaturaId");
                });

            modelBuilder.Entity("ProyectoV2.Models.Estudiante", b =>
                {
                    b.HasOne("ProyectoV2.Models.CargaAcademica", "CargaAcademica")
                        .WithMany()
                        .HasForeignKey("CargaAcademicaid");
                });

            modelBuilder.Entity("ProyectoV2.Models.Grupo", b =>
                {
                    b.HasOne("ProyectoV2.Models.Asignatura", "Asignatura")
                        .WithMany()
                        .HasForeignKey("AsignaturaId");

                    b.HasOne("ProyectoV2.Models.Docente", "Docente")
                        .WithMany()
                        .HasForeignKey("DocenteId");
                });

            modelBuilder.Entity("ProyectoV2.Models.Programa", b =>
                {
                    b.HasOne("ProyectoV2.Models.Facultad", "Facultad")
                        .WithMany()
                        .HasForeignKey("FacultadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProyectoV2.Models.Tema", b =>
                {
                    b.HasOne("ProyectoV2.Models.EjeTematico", null)
                        .WithMany("Temas")
                        .HasForeignKey("EjeTematicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
